const categories = [
    {
      name: "Technology & Science",
      subcategories: [
        "AI & Machine Learning",
        "Software Development",
        "Cybersecurity",
        "Robotics",
        "Blockchain & Cryptocurrency",
        "Space Exploration",
        "Quantum Computing",
        "Data Science",
        "Ethical Hacking",
        "Cloud Computing",
        "Virtual Reality (VR)",
        "Augmented Reality (AR)",
        "3D Printing",
        "Biotechnology",
        "Renewable Energy",
        "Gadgets & Tech Reviews",
        "Coding & Programming",
        "Web Development",
        "Mobile Apps",
        "UX/UI Design",
        "Artificial Intelligence Ethics",
        "Cyber-Physical Systems",
        "Natural Language Processing",
        "Data Privacy",
        "Augmented Reality in Medicine",
        "AI-Powered Automation",
        "Neural Networks",
        "Smart Cities",
        "Blockchain Security",
        "Digital Twins",
        "Tech Startups",
        "AI-Driven Healthcare",
        "Sustainable Tech",
        "Nano-Technology",
        "Tech Entrepreneurship",
        "FinTech",
        "Energy-Efficient Computing",
        "Tech Innovations",
        "Smart Devices",
        "AI in Education"
      ]
    },
    {
      name: "Gaming & Entertainment",
      subcategories: [
        "PC Gaming",
        "Console Gaming",
        "Mobile Gaming",
        "Esports",
        "Retro Gaming",
        "VR Gaming",
        "Streaming (Twitch, YouTube)",
        "Anime & Manga",
        "Sci-Fi & Fantasy",
        "Horror Movies",
        "Comedy Shows",
        "Stand-Up Comedy",
        "Movie Reviews",
        "TV Series Binge-Watching",
        "K-Pop",
        "EDM & Festivals",
        "Music Production",
        "Hip-Hop Culture",
        "Guitar & Instruments",
        "Concerts & Live Music",
        "Game Development",
        "Indie Games",
        "Game Modding",
        "Storytelling in Games",
        "Speedrunning",
        "Game Design Theory",
        "Mobile Game Development",
        "Esports Management",
        "Game Art",
        "Streaming Setup & Equipment",
        "Game Development Tutorials",
        "Interactive Storytelling",
        "Game Mechanics",
        "VR Game Development",
        "Game Music & Soundtracks",
        "Game Criticism",
        "Classic Video Games",
        "Gaming Cultures",
        "Cosplay Photography",
        "Game Localization"
      ]
    },
    {
      name: "Health & Wellness",
      subcategories: [
        "Fitness & Workouts",
        "Weightlifting",
        "Yoga & Meditation",
        "Mental Health",
        "Nutrition & Dieting",
        "Healthy Recipes",
        "Biohacking",
        "Self-Improvement",
        "Running & Marathon Training",
        "Cycling",
        "Home Workouts",
        "Personal Development",
        "Skin Care & Beauty",
        "Mindfulness",
        "Sleep Optimization",
        "Stress Management",
        "Therapy & Counseling",
        "Life Coaching",
        "Holistic Healing",
        "Supplements & Wellness",
        "Health Tech",
        "Mental Health Apps",
        "Biofeedback",
        "Nootropics",
        "Sleep Disorders",
        "Alternative Therapies",
        "Fitness Wearables",
        "Women’s Health",
        "Digital Health Tools",
        "Chronic Pain Management",
        "Sports Medicine",
        "Fitness Nutrition",
        "Workplace Wellness",
        "Mental Health for Teens",
        "Healthy Aging",
        "Mind-Body Connection",
        "Health Coaching",
        "Pain Relief Strategies",
        "Holistic Nutrition",
        "Weight Loss Motivation"
      ]
    },
    {
      name: "Business & Finance",
      subcategories: [
        "Entrepreneurship",
        "Investing & Stocks",
        "Real Estate",
        "Personal Finance",
        "Passive Income",
        "Side Hustles",
        "Cryptocurrency Trading",
        "Startups & Innovation",
        "Venture Capital",
        "Leadership & Management",
        "Freelancing",
        "Productivity Hacks",
        "Marketing & Branding",
        "Social Media Growth",
        "E-commerce & Dropshipping",
        "NFTs & Web3",
        "Business Networking",
        "Public Speaking",
        "Career Growth",
        "Negotiation Skills",
        "Financial Technology",
        "Crowdfunding",
        "Corporate Social Responsibility",
        "Wealth Management",
        "Financial Independence",
        "Financial Planning",
        "Financial Inclusion",
        "Impact Investing",
        "Sustainable Business Practices",
        "Mergers & Acquisitions",
        "Venture Debt",
        "Asset Management",
        "Regulatory Compliance",
        "Real Estate Investment Trusts",
        "Personal Budgeting",
        "Banking Innovation",
        "Cryptocurrency Regulations",
        "Digital Banking",
        "Social Entrepreneurship",
        "Public-Private Partnerships"
      ]
    },
    {
      name: "Lifestyle & Hobbies",
      subcategories: [
        "Fashion & Style",
        "Streetwear Culture",
        "Luxury Brands",
        "Minimalism",
        "DIY & Crafts",
        "Journaling",
        "Bullet Journaling",
        "Stationery & Calligraphy",
        "Digital Art",
        "Tattoos & Piercings",
        "Photography",
        "Videography",
        "Home Décor",
        "Interior Design",
        "Collectibles & Antiques",
        "Thrifting & Vintage Fashion",
        "Gardening & Plants",
        "Astrology",
        "Tarot & Spirituality",
        "Manifestation",
        "Upcycling & Repurposing",
        "Home Brewing",
        "Making Your Own Clothes",
        "DIY Home Decor",
        "Board Game Design",
        "Travel Hacking",
        "Vintage Cars",
        "Street Photography",
        "Birdwatching",
        "Stargazing",
        "Urban Gardening",
        "Sustainable Fashion",
        "Tiny Houses",
        "Cooking with Kids",
        "Weekend Projects",
        "Sewing & Quilting",
        "Tinkering & Inventing",
        "Local Food Culture",
        "Cultural Heritage Preservation",
        "Geocaching"
      ]
    },
    {
      name: "Travel & Adventure",
      subcategories: [
        "Backpacking",
        "Road Trips",
        "Luxury Travel",
        "Budget Travel",
        "Digital Nomad Lifestyle",
        "Camping & Hiking",
        "Beach Destinations",
        "City Exploration",
        "Cultural Experiences",
        "Food Tourism",
        "Solo Travel",
        "Group Travel",
        "Van Life",
        "Air Travel Hacks",
        "Extreme Sports",
        "Scuba Diving",
        "Mountain Climbing",
        "Wildlife & Safaris",
        "Eco-Tourism",
        "Travel Photography",
        "Cultural Immersion",
        "Volunteer Travel",
        "Expedition Travel",
        "Extreme Travel Destinations",
        "Digital Detox Travel",
        "Festival Travel",
        "Historical Site Exploration",
        "Desert Exploration",
        "Cold Weather Travel",
        "Luxury Cruises",
        "Adventure Photography",
        "Hiking Trails",
        "Mountain Resorts",
        "Forest Retreats",
        "Glamping",
        "Eco-Friendly Resorts",
        "International Backpacking",
        "Road Biking Tours",
        "Wildlife Conservation Travel",
        "Rural Tourism"
      ]
    },
    {
      name: "Food & Drink",
      subcategories: [
        "Cooking & Recipes",
        "Baking",
        "Vegan Lifestyle",
        "Keto & Low-Carb",
        "Coffee Culture",
        "Tea Lovers",
        "Wine & Fine Dining",
        "Craft Beer",
        "Street Food",
        "Fermentation & Pickling",
        "BBQ & Grilling",
        "Spicy Food Challenge",
        "Farm-to-Table Cooking",
        "Cultural Cuisine Exploration",
        "Healthy Meal Prepping",
        "Dessert & Sweets",
        "Chocolate & Confections",
        "Sushi & Japanese Cuisine",
        "Indian Spices & Cooking",
        "French Pastries",
        "Fusion Cuisine",
        "Foraging",
        "Culinary Arts",
        "Gourmet Cooking",
        "Slow Cooking",
        "Food Photography",
        "Fermented Foods",
        "Sustainable Seafood",
        "Molecular Gastronomy",
        "Food Plating",
        "Barbecue Styles",
        "Farm-to-Fork",
        "Healthy Desserts",
        "Grilled Meats",
        "Vegan Desserts",
        "Food for Athletes",
        "Gastronomy Science",
        "Drink Pairing",
        "Restaurant Review",
        "Farmers’ Markets"
      ]
    },
    {
      name: "Art & Creativity",
      subcategories: [
        "Painting",
        "Sketching & Drawing",
        "Graphic Design",
        "Calligraphy & Lettering",
        "Animation & Motion Graphics",
        "Graffiti & Street Art",
        "Watercolor Painting",
        "Printmaking",
        "Collage Art",
        "Portrait Drawing",
        "Sculpting & Pottery",
        "Concept Art",
        "Fashion Illustration",
        "Comic Book Art",
        "3D Modeling",
        "Character Design",
        "Mixed Media Art",
        "DIY Crafts",
        "Creative Writing",
        "Poetry & Spoken Word",
        "3D Art Installations",
        "Conceptual Art",
        "Tattoo Art",
        "Fashion Photography",
        "Viral Art",
        "Film Making",
        "Sculpture Art",
        "Digital Storytelling",
        "Art Collecting",
        "Abstract Art",
        "Street Photography",
        "Handmade Art",
        "Bookbinding",
        "Experimental Art",
        "Kinetic Art",
        "Public Art Projects",
        "Art Curation",
        "Folk Art",
        "Surrealism",
        "Film Photography"
      ]
    },
    {
      name: "Sports & Outdoors",
      subcategories: [
        "Basketball",
        "Soccer",
        "American Football",
        "Baseball",
        "Tennis",
        "Golf",
        "Formula 1 & Motorsports",
        "Skateboarding",
        "Snowboarding",
        "Surfing",
        "Rock Climbing",
        "Martial Arts & MMA",
        "Boxing",
        "Yoga & Pilates",
        "Running & Marathons",
        "Cycling",
        "Fishing",
        "Hunting",
        "Parkour & Free Running",
        "Archery",
        "Parkour",
        "CrossFit",
        "Lacrosse",
        "Ultimate Frisbee",
        "Cyclocross",
        "Surf Culture",
        "Skiing",
        "Stand-Up Paddleboarding",
        "Triathlons",
        "Competitive Swimming",
        "Trail Running",
        "Sports Science",
        "Rock Climbing Gear",
        "Kayaking",
        "Mountain Biking",
        "Motocross",
        "Off-Road Running",
        "Deep Sea Fishing",
        "Track and Field",
        "Equestrian Sports"
      ]
    },
    {
      name: "Science & Education",
      subcategories: [
        "Space & Astronomy",
        "Neuroscience",
        "Psychology",
        "History & Ancient Civilizations",
        "Philosophy",
        "Mythology",
        "Linguistics",
        "Sociology",
        "Physics",
        "Chemistry",
        "Biology & Evolution",
        "Geology & Earth Science",
        "Political Science",
        "Anthropology",
        "Archaeology",
        "Mathematics",
        "Science Fiction & Futurism",
        "Ethical Debates",
        "Economics",
        "Artificial Intelligence Ethics",
        "STEM Education",
        "Human Evolution",
        "Astronomical Discoveries",
        "Technology in Education",
        "Math Education",
        "Science for Kids",
        "Virtual Labs",
        "STEM Outreach Programs",
        "Ecology & Conservation",
        "Paleontology",
        "Scientific Writing",
        "Geospatial Science",
        "Biology Research",
        "Physics Education",
        "Open Access Research",
        "Philosophy of Science",
        "Science Literacy",
        "Research Ethics",
        "Innovation in Education",
        "Data Science Education"
      ]
    },
    {
      name: "Social & Cultural Topics",
      subcategories: [
        "Feminism & Gender Studies",
        "LGBTQ+ Community",
        "Social Justice",
        "Cultural Heritage",
        "Human Rights",
        "Mental Health Awareness",
        "Disability Advocacy",
        "Environmental Activism",
        "Ethical Consumerism",
        "Diversity & Inclusion",
        "Indigenous Cultures",
        "Humanitarian Work",
        "Philanthropy",
        "Volunteerism",
        "Animal Rights",
        "Climate Change",
        "Zero-Waste Living",
        "Anti-Racism",
        "Fair Trade Practices",
        "Public Policy",
        "Globalization",
        "Cultural Integration",
        "Racial Justice",
        "Social Impact Investing",
        "Youth Activism",
        "Feminist Theory",
        "Humanitarian Aid",
        "Cultural Preservation",
        "Community Building",
        "Human Rights Education",
        "Gender Fluidity",
        "Collective Bargaining",
        "Civil Liberties",
        "Restorative Justice",
        "The Digital Divide",
        "Cultural Diplomacy",
        "Collective Action",
        "Humanitarian Work",
        "Ethical Fashion",
        "Social Media Activism"
      ]
    },
    {
      name: "Miscellaneous Interests",
      subcategories: [
        "ASMR",
        "Memes & Internet Culture",
        "Conspiracy Theories",
        "True Crime",
        "Paranormal Investigations",
        "Ghost Hunting",
        "Fan Fiction",
        "Cosplay",
        "Role-Playing Games (RPGs)",
        "Collecting Sneakers",
        "Car Enthusiasts",
        "Tiny Homes & Off-Grid Living",
        "Cryptocurrency Memes",
        "Alternative Lifestyles",
        "DIY Home Improvement",
        "Foraging & Survival Skills",
        "Personal Security & Self-Defense",
        "Board Games & Puzzles",
        "Magic & Illusions",
        "Secret Societies",
        "Productivity & Work Life",
        "Time Management",
        "Deep Work & Focus",
        "Remote Work Culture",
        "Office Productivity Hacks",
        "Career Switching",
        "Resume & Interview Tips",
        "Work-Life Balance",
        "Startup Culture",
        "Side Hustles",
        "Passive Income Strategies",
        "Survivalism",
        "Urban Exploration",
        "Secret Codes",
        "Psychic Phenomena",
        "Superheroes",
        "Alternative Health",
        "Street Magic",
        "Etymology",
        "Wildlife Photography",
        "Collecting Antiques",
        "Treasure Hunts",
        "Freelance Writing",
        "Creative Coding",
        "Science Fiction Writing",
        "Genealogy",
        "Astrophotography",
        "Maker Movement",
        "Urban Legends",
        "Superstition",
        "Conspiracy Theory Debunking"
      ]
    }
  ];